server:
  port: 10086
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      #eureka高可用
      #defaultZone: http://127.0.0.1:10087/eureka
      defaultZone: http://127.0.0.1:10086/eureka
    #不注册本身
    register-with-eureka: false

  server:
    #失效剔除，默认为60秒
    eviction-interval-timer-in-ms: 30000
    #自我保护 默认和不写都是为true 意思是服务没有按时心跳续约，（可是是因为网络延时）
    #因此可能服务并没有宕机，
    #eureka会统计最近15分钟心跳续约的比例是否低于85%
    enable-self-preservation: true

